### ➕ Crear Document Type


@baseUrl = http://localhost:3000/api

### 🔐 LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###

@accessToken = {{login.response.body.accessToken}}


POST {{baseUrl}}/documents-types
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "code": "NC",
  "description": "Nota de credito compras",
  "direction": -1,
  "affects_stock": false,
  "affects_accounting": true,
  "affects_tax_book": true,
  "active": true,
  "document_sequence_id": "4abaaa4d-38be-49b4-9dc0-58b8fcddc0be"
}