deploy:
  - docker stop asterisksuite_backend || true
  - docker rm asterisksuite_backend || true
  - docker run -d --name asterisksuite_backend \
    -e PORT=3000 \
    -e PG_USER=postgres \
    -e PG_PASSWORD=postgres \
    -e PG_DATABASE=va9000-alona \
    -e PG_PORT=5433 \
    -e JWT_SECRET=donandresasterisk \
    -e DATABASE_URL="postgresql://postgres:postgres@localhost:5433/va9000-alona?schema=test9000" \
    -l "traefik.enable=true" \
    -l "traefik.http.routers.asterisksuite_backend.rule=Host(`apialona.asterisksuite.cloud`)" \
    -l "traefik.http.services.asterisksuite_backend.loadbalancer.server.port=3000" \
    asterisksuite_backend
