# @baseUrl = http://localhost:3000/api
# @baseUrl = https://apidonandres.asterisksuite.cloud/api

 @baseUrl = https://devdonandres.asterisksuite.cloud/api

@corridorId = 89989adf-71c2-496a-8035-ea6c5190a451
@companyId = a060f7ff-0281-4df4-b5b3-cbdf940be31e
@originLocationId = 00000000-0000-0000-0000-000000000000
@destinationLocationId = 00000000-0000-0000-0000-000000000000
@stop1 = 00000000-0000-0000-0000-000000000000
@stop2 = 00000000-0000-0000-0000-000000000000
###
# ==============================
# 🔐 LOGIN
# ==============================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}
###
@token = {{login.response.body.accessToken}}

###
# Crear corredor
POST {{baseUrl}}/corridors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "company_id": "{{companyId}}",
  "name": "Corredor Córdoba - Rosario",
  "origin_location_id": "{{originLocationId}}",
  "destination_location_id": "{{destinationLocationId}}",
  "is_template": true,
  "stops": [
    {
      "location_id": "{{stop1}}",
      "stop_order": 1
    },
    {
      "location_id": "{{stop2}}",
      "stop_order": 2
    }
  ]
}

###
# Obtener todos los corredores
GET {{baseUrl}}/corridors
Authorization: Bearer {{token}}

###
# Obtener solo templates
GET {{baseUrl}}/corridors/templates
Authorization: Bearer {{token}}

###
# Obtener corredor por id
GET {{baseUrl}}/corridors/{{corridorId}}
Authorization: Bearer {{token}}

###
# Obtener ruta completa del corredor
GET {{baseUrl}}/corridors/{{corridorId}}/route
Authorization: Bearer {{token}}

###
# Actualizar corredor
PATCH {{baseUrl}}/corridors/{{corridorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Corredor Córdoba - Buenos Aires",
  "is_template": false
}

###
# Eliminar corredor
DELETE {{baseUrl}}/corridors/{{corridorId}}
Authorization: Bearer {{token}}