export enum MaintenanceAssetType {
  VEHICLE = 'VEHICLE',
  TIRE = 'TIRE',
  BATTERY = 'BATTERY',
  ENGINE = 'ENGINE',
  TRANSMISSION = 'TRANSMISSION',
  DIFFERENTIAL = 'DIFFERENTIAL',
  OTHER_COMPONENT = 'OTHER_COMPONENT',
}

export enum MaintenancePriority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum MaintenanceStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_PARTS = 'WAITING_PARTS',
  WAITING_SUPPLIER = 'WAITING_SUPPLIER',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MaintenanceType {
  CORRECTIVE = 'CORRECTIVE',
  PREVENTIVE = 'PREVENTIVE',
  PREDICTIVE = 'PREDICTIVE',
  INSPECTION = 'INSPECTION',
  SCHEDULED = 'SCHEDULED',
}

export enum MaintenanceCategory {
  ENGINE = 'ENGINE',
  TRANSMISSION = 'TRANSMISSION',
  BRAKES = 'BRAKES',
  SUSPENSION = 'SUSPENSION',
  STEERING = 'STEERING',
  ELECTRICAL = 'ELECTRICAL',
  COOLING = 'COOLING',
  LUBRICATION = 'LUBRICATION',
  TIRES = 'TIRES',
  BODY = 'BODY',
  LIGHTING = 'LIGHTING',
  TRAILER = 'TRAILER',
  OTHER = 'OTHER',
}

export enum MaintenanceTaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
}

export enum TireMovementType {
  PURCHASE = 'PURCHASE',
  RECEIPT = 'RECEIPT',
  TRANSFER = 'TRANSFER',
  INSTALLATION = 'INSTALLATION',
  REMOVAL = 'REMOVAL',
  ROTATION = 'ROTATION',
  REPAIR = 'REPAIR',
  RETREAD = 'RETREAD',
  WAREHOUSE_ENTRY = 'WAREHOUSE_ENTRY',
  WAREHOUSE_EXIT = 'WAREHOUSE_EXIT',
  SCRAP = 'SCRAP',
  SALE = 'SALE',
}

export enum TirePositionSide {
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
}

export enum PlanIntervalType {
  INTERVAL_KM = 'INTERVAL_KM',
  INTERVAL_DAYS = 'INTERVAL_DAYS',
  INTERVAL_MONTHS = 'INTERVAL_MONTHS',
  FIXED_DATE = 'FIXED_DATE',
}

export enum TireStatus {
  IN_STOCK = 'IN_STOCK',
  INSTALLED = 'INSTALLED',
  IN_REPAIR = 'IN_REPAIR',
  SCRAPPED = 'SCRAPPED',
  SOLD = 'SOLD',
}

export enum TireLocationType {
  WAREHOUSE = 'WAREHOUSE',
  VEHICLE = 'VEHICLE',
  TIRE_SHOP = 'TIRE_SHOP',
  SCRAP = 'SCRAP',
  CUSTOMER = 'CUSTOMER',
}