# @baseUrl = https://apidonandres.asterisksuite.cloud/api
 @baseUrl = http://localhost:3000/api

@refreshToken = d9d9512c89e5c626d92933acaf8d4de09a0641afb2bdc843e05f4240bbb76c1c7be90fc90bd7fa4153f8469e69153dc58df600e184c2e86bf09e2588d48683a0
###
# ==============================
# 🔐 LOGIN
# ==============================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###
@accessToken = {{login.response.body.accessToken}}
### ==================================================
### Crear Location
### POST /locations
### ==================================================

POST {{baseUrl}}/locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "city": "Leones",
  "province": "Córdoba",
  "country": "Argentina",
  "postalCode": "5900"
}


### ==================================================
### Listar todas las Locations
### GET /locations
### ==================================================

GET {{baseUrl}}/locations
Authorization: Bearer {{accessToken}}


### ==================================================
### Obtener Location por ID (incluye warehouses)
### GET /locations/:id
### ==================================================

GET {{baseUrl}}/locations/UUID_DE_LA_LOCATION
Authorization: Bearer {{accessToken}}


### ==================================================
### Actualizar Location
### PATCH /locations/:id
### ==================================================

PATCH {{baseUrl}}/locations/9f9fd44b-9d29-4113-ad09-ccb65e9c22e4
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
"address": "agus",
    "city": "Rosario",
    "province": "Santa Fe",
    "country": "Argentina",
    "latitude": null,
    "longitude": null
}


### ==================================================
### Eliminar Location
### DELETE /locations/:id
### ==================================================

DELETE {{baseUrl}}/trash/locations/9f9fd44b-9d29-4113-ad09-ccb65e9c22e4
Authorization: Bearer {{accessToken}}


### ==================================================
### Restaurar Location
### PATCH /locations/:id
### ==================================================

PATCH {{baseUrl}}/trash/locations/9f9fd44b-9d29-4113-ad09-ccb65e9c22e4
Authorization: Bearer {{accessToken}}