# @baseUrl = http://localhost:3000/api
@baseUrl = https://api.asterisksuite.cloud/api

@refreshToken = d9d9512c89e5c626d92933acaf8d4de09a0641afb2bdc843e05f4240bbb76c1c7be90fc90bd7fa4153f8469e69153dc58df600e184c2e86bf09e2588d48683a0

###
# ==============================
# 📝 REGISTER
# ==============================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Administrador",
  "email": "admin@mail.com",
  "password": "123456",
  "role": "admin"
}

###
# ==============================
# 🔐 LOGIN
# ==============================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###  <-- este separador es clave

@accessToken = {{login.response.body.accessToken}}
@refreshToken = {{login.response.body.refreshToken}}
###
# ==============================
# 🔄 REFRESH TOKEN
# ==============================
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT (revoca 1 sesión)
# ==============================
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT ALL DEVICES
# ==============================
POST {{baseUrl}}/auth/logout-all
Authorization: Bearer {{accessToken}}

###
# ==============================
# 🔑 CAMBIAR PASSWORD
# ==============================
POST {{baseUrl}}/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "pecha2025",
  "newPassword": "123456"
}

###
# ==============================
# 👤 USUARIO ACTUAL
# ==============================
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
