@baseUrl = https://apidonandres.asterisksuite.cloud/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZWZhYmYxYi1jODlkLTQ1ZTgtODNhOS1lNTIzNTJlZDAxNTkiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJjb21wYW55SWQiOm51bGwsImlhdCI6MTc3MjU3NDgzNSwiZXhwIjoxNzcyNTc1NzM1fQ.LqLpp30xlnMpuctrvPmYmuHrCs5hFW48oKTqBCggPJI
@warehouseId = a17c6178-5fb2-4815-8231-e93f14cee732
@productId = d999cb04-81fb-4f3a-8d84-9e6d32b77848
@userId = fefabf1b-c89d-45e8-83a9-e52352ed0159

###
# ==============================
# 🔐 LOGIN
# ==============================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

### =====================================================
### Obtener stock actual de un depósito
### GET /warehouse/stock/:warehouseId
### =====================================================

GET {{baseUrl}}/warehouse/stock/{{warehouseId}}
Authorization: Bearer {{accessToken}}


### =====================================================
### Obtener movimientos de stock de un depósito
### GET /warehouse/stock/:warehouseId/movements
### =====================================================

GET {{baseUrl}}/warehouse/stock/{{warehouseId}}/movements
Authorization: Bearer {{accessToken}}


### =====================================================
### Crear movimiento de ingreso (IN)
### POST /warehouse/stock/movement
### =====================================================

POST {{baseUrl}}/warehouse/stock/movement
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "warehouse_id": "{{warehouseId}}",
  "product_id": "{{productId}}",
  "movement_type": "PURCHASE",
  "direction": "IN",
  "quantity": "100.50",
  "reference_type": "PURCHASE_ORDER",
  "reference_id": "UUID_OPCIONAL",
  "notes": "Ingreso por compra proveedor",
  "created_by": "{{userId}}"
}


### =====================================================
### Crear movimiento de egreso (OUT)
### POST /warehouse/stock/movement
### =====================================================

POST {{baseUrl}}/warehouse/stock/movement
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "warehouse_id": "{{warehouseId}}",
  "product_id": "{{productId}}",
  "movement_type": "SALE",
  "direction": "OUT",
  "quantity": "20.00",
  "reference_type": "SALES_ORDER",
  "reference_id": "UUID_OPCIONAL",
  "notes": "Salida por venta",
  "created_by": "{{userId}}"
}