@baseUrl = http://localhost:3000/api

########################################################

# USUARIO A

########################################################

# @name registerA

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
"name": "Usuario Dev",
"email": "usuariodev@test.com",
"password": "123456",
"role": "PLATFORM_OWNER"
}

###

# @name loginA

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "usuariodev@test.com",
"password": "123456"
}

###

@tokenA = {{loginA.response.body.accessToken}}

########################################################

# EMPRESA A

########################################################

# @name companyA

POST {{baseUrl}}/companies
Authorization: Bearer {{tokenA}}
Content-Type: application/json

{
"name": "Empresa Dev",
"subdomain": "dev",
"schemaName": "tenant_dev"
}

########################################################

# PRODUCTO EMPRESA A

########################################################

# @name createProductA

POST {{baseUrl}}/master-data/products
Authorization: Bearer {{tokenA}}
x-tenant: dev
Content-Type: application/json

{
"name": "Producto Empresa A",
"active": true
}

########################################################

# CONSULTAR PRODUCTOS EMPRESA A

########################################################

GET {{baseUrl}}/master-data/products
Authorization: Bearer {{tokenA}}
x-tenant: empresaa

###

GET {{baseUrl}}/auth/me
Authorization: Bearer {{tokenA}}
x-tenant: empresaa

###
