//@url= https://apialona.asterisksuite.cloud/api
@url= http://localhost:3000/api

@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDYiLCJ1c2VybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTc2ODY1NjY0NywiZXhwIjoxNzY4NzQzMDQ3fQ.1b7kkWO_lr8hhn2bT2e7kDQyTkA0SEN1L5xIjlbugew

### 1. Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "Administrador",
  "password": "1234"
}
###login alona

POST {{url}}/login
Content-Type: application/json

{
    "username": "Administrador",
    "password": "1234"
}

### trae todos los articulos pero lo basico
GET {{url}}/articulos/index
Authorization: {{token}}

### trae todos los articulos con las especificaciones que les pasemos
GET {{url}}/articulos/index?expand=precio,espec
Authorization: {{token}}

###
GET {{url}}/articulos/arbol-costos/1118
Authorization: {{token}}

###
GET http://localhost:3008/articulos/compuestos/1118
Authorization: {{token}}

###
GET http://localhost:3008/articulos/1133
Authorization: {{token}}
