### 1. Login
POST http://localhost:3008/api/login
Content-Type: application/json

{
  "username": "Administrador",
  "password": "1234"
}


###
GET http://localhost:3008/articulos/index
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzOCIsInVzZXJuYW1lIjoiQWRtaW5pc3RyYWRvciIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNzY1Mjg3NDkwLCJleHAiOjE3NjUzNzM4OTB9.lCHyRXs6VPwcaIvGZFD6Iftm2jXzwyl8afPtlgJuRN8

###
GET http://localhost:3008/articulos/arbol-costos/1118
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDYiLCJ1c2VybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTc2NTI4NzgzNCwiZXhwIjoxNzY1Mzc0MjM0fQ.E4DJIe_6bh5uLFHZX3MMThEiWT5spaimMIHXxnIDyzY

###
GET http://localhost:3008/articulos/compuestos/1118
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDYiLCJ1c2VybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTc2NTI4NzgzNCwiZXhwIjoxNzY1Mzc0MjM0fQ.E4DJIe_6bh5uLFHZX3MMThEiWT5spaimMIHXxnIDyzY

###
GET http://localhost:3008/articulos/1133
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDYiLCJ1c2VybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTc2NTI4NzgzNCwiZXhwIjoxNzY1Mzc0MjM0fQ.E4DJIe_6bh5uLFHZX3MMThEiWT5spaimMIHXxnIDyzY
