@baseUrl = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZjZmMGQ5Ni1lOGUyLTQ5ODAtOGFiNC01NmZhNGEwZTFlZTQiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJjb21wYW55SWQiOiJjMDdjZmYxOS0xNDEyLTRkMTItOGVlMC0wODlkMmNjYWM3MjkiLCJpYXQiOjE3NzI0ODY1NDYsImV4cCI6MTc3MjQ4NzQ0Nn0.TfBa2Jit1A3Da37sZrSt6JbLMlBBuNzAGSjE-_xzbs4

@refreshToken = 96bb970eaaef9fb65f9366f46602b43e04c6888b48391add1971fa3abda09ca7cf0ccaaa8b0b73b131e072fd6adbb96524ec0c0d85c6fea8f2600904cf13ec8a
@partyId = b8c46fe5-c77a-4ea3-aed5-3d73e5e27915

###
# ==============================
# 🔐 LOGIN
# ==============================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}


### =====================================================
### Crear Business Party
### POST /master-data/business-parties
### =====================================================

POST {{baseUrl}}/master-data/business-parties
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
"active": true,
"company_id":"c07cff19-1412-4d12-8ee0-089d2ccac729",
"email":"agustinyedro@gmail.com",
"name":"Agustin Yedro",
"phone":"3513075338",
"tax_id":"303030030",
"type":"supplier"
}




### =====================================================
### Listar Business Parties por empresa
### GET /master-data/business-parties?company_id=
### =====================================================

GET {{baseUrl}}/master-data/business-parties?company_id={{companyId}}
Authorization: Bearer {{accessToken}}


### =====================================================
### Obtener Business Party por ID
### (incluye party_locations y locations)
### GET /master-data/business-parties/:id
### =====================================================

GET {{baseUrl}}/master-data/business-parties/{{partyId}}
Authorization: Bearer {{accessToken}}


### =====================================================
### Actualizar Business Party
### PATCH /master-data/business-parties/:id
### =====================================================

PATCH {{baseUrl}}/master-data/business-parties/{{partyId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Cliente Demo Actualizado SA",
  "phone": "3514448888",
  "email": "nuevoemail@demo.com"
}


### =====================================================
### Soft Delete (active = false)
### DELETE /master-data/business-parties/:id
### =====================================================

DELETE {{baseUrl}}/master-data/business-parties/{{partyId}}
Authorization: Bearer {{accessToken}}