@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjhjNWE4Yy1mZWFhLTQ4NWUtYmMyYS05YzMwYjFkNjNiYmUiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJjb21wYW55SWQiOm51bGwsImlhdCI6MTc3MjI0MzYxMCwiZXhwIjoxNzcyMjQ0NTEwfQ.67si5kMQBBSBgMNxqaDNdWOtbmDNWya57GQJPwkx1M8
@refreshToken = d9d9512c89e5c626d92933acaf8d4de09a0641afb2bdc843e05f4240bbb76c1c7be90fc90bd7fa4153f8469e69153dc58df600e184c2e86bf09e2588d48683a0


###
# ==============================
# 🔐 LOGIN
# ==============================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "12345678"
}
###
# Crear compañía
POST {{baseUrl}}/api/companies
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Don Andres",
  "taxId": "30-00000000-0",
  "address": "Ruta 9 Km 200",
  "phone": "123456789",
  "email": "admin@donandres.com"
}


###
# Obtener todas las depositos
GET {{baseUrl}}/api/warehouses
Authorization: Bearer {{token}}
###
# Obtener todas las compañías
GET {{baseUrl}}/api/companies
Authorization: Bearer {{token}}

###
# Obtener compañía por ID
GET {{baseUrl}}/api/companies/8efc304c-d882-41a9-b0e2-6ace231a2c8f
Authorization: Bearer {{token}}

###
# Actualizar compañía
PATCH {{baseUrl}}/api/companies/8efc304c-d882-41a9-b0e2-6ace231a2c8f
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "phone": "111222333"
}

###
# Eliminar compañía
DELETE {{baseUrl}}/companies/1
Authorization: Bearer {{token}}
