# @url= https://apialona.asterisksuite.cloud/api
@url= http://localhost:3000/api

@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNDYiLCJ1c2VybmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTc3MDc1NDM5OCwiZXhwIjoxNzcwODQwNzk4fQ.NZThiSbHK8ip11hm7t8sDr_kyJkX1xglB7h_Qd5qUJg

### 1. Login
### Importar Artículo - Precio
POST {{url}}/data-import/articulo-precio
Authorization: {{token}}


file=@C:\Users\USURIO\Downloads\prueba-data-importer.xlsx
