@baseUrl = http://localhost:3000/api

### 🔐 LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###

@accessToken = {{login.response.body.accessToken}}

### Crear secuencia
POST {{baseUrl}}/document-sequence
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Facturas A",
  "automatic": true,
  "point_of_sale": "0001",
  "current_number": 0,
  "prefix": "A",
  "active": true
}