### ➕ Crear Document Type


@baseUrl = http://localhost:3000/api

### 🔐 LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###

@accessToken = {{login.response.body.accessToken}}


POST {{baseUrl}}/documents-types
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "document_sequence_id": "45b6b231-4de2-41c4-9b5d-ada23d451298",
  "code": "COM",
  "description": "Factura de compra",
  "direction": -1,
  "affects_stock": true,
  "affects_accounting": true,
  "affects_tax_book": true,
  "active": true
}

