@baseUrl = https://apidonandres.asterisksuite.cloud/api

@documentTypeId = 499866a1-97b0-4c6a-8b9b-bea198bd1be5


###
# ==============================
# 🔐 LOGIN
# ==============================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}
###  <-- este separador es clave

@accessToken = {{login.response.body.accessToken}}
### =====================================================
### Crear Tipo de Documento (VEHICLE)
### POST /logistica/document-types
### =====================================================

POST {{baseUrl}}/logistica/document-types
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "VTV",
  "entity": "VEHICLE"
}


### =====================================================
### Crear Tipo de Documento (DRIVER)
### =====================================================

POST {{baseUrl}}/logistica/document-types
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Licencia profesional",
  "entity": "DRIVER"
}


### =====================================================
### Listar todos los tipos activos
### GET /logistica/document-types
### =====================================================

GET {{baseUrl}}/logistica/document-types
Authorization: Bearer {{accessToken}}


### =====================================================
### Listar por entidad
### GET /logistica/document-types?entity=VEHICLE
### =====================================================

GET {{baseUrl}}/logistica/document-types?entity=VEHICLE
Authorization: Bearer {{accessToken}}

#### =====
PATCH {{baseUrl}}/logistica/document-types/e90d7345-dbe6-4eb6-8034-9980359729e8
Authorization: Bearer {{accessToken}}

{
  "entity": "VEHICLE"
}


### =====================================================
### Desactivar tipo de documento (soft delete)
### PATCH /logistica/document-types/:id/deactivate
### =====================================================

PATCH {{baseUrl}}/logistica/document-types/{{documentTypeId}}/deactivate
Authorization: Bearer {{accessToken}}