@baseUrl = http://localhost:3000/api

### 🔐 LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###

@accessToken = {{login.response.body.accessToken}}

### ➕ Crear Tax
POST {{baseUrl}}/taxes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "code": "IVA21",
  "name": "IVA 21%",
  "tax_type": "IVA",
  "rate": 21,
  "is_percentage": true,
  "active": true,
  "calculation_level": "document"
}

###

### 📋 Listar Taxes por empresa
GET {{baseUrl}}/taxes?id 
Authorization: Bearer {{accessToken}}

###

### ✏️ Actualizar Tax
PATCH {{baseUrl}}/taxes/6f3a600a-61ec-4c3a-aa5a-780ac5d5c4e8
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "code": "Excento",
  "rate": -10
  
}