@baseUrl = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjhjNWE4Yy1mZWFhLTQ4NWUtYmMyYS05YzMwYjFkNjNiYmUiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzIwNTE3NDYsImV4cCI6MTc3MjA1MjY0Nn0.pvB7x45WNMfcBBfdxdFZLAacqJcA4z0WiSLNPrE4bmw
@refreshToken = 3eb0e946b62f528d425d78f15e7818a0380d03dfee424df7985502ac17cc64419fbac978d79996c5d1446201ae1828417f9233979ec6fb7bf60ed61916b0d8be

###
# ==============================
# 📝 REGISTER
# ==============================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Administrador",
  "email": "admin@mail.com",
  "password": "123456",
  "role": "admin",
  "companyId": null
}

###
# ==============================
# 🔐 LOGIN
# ==============================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###
# ==============================
# 🔄 REFRESH TOKEN
# ==============================
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT (revoca 1 sesión)
# ==============================
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT ALL DEVICES
# ==============================
POST {{baseUrl}}/auth/logout-all
Authorization: Bearer {{accessToken}}

###
# ==============================
# 🔑 CAMBIAR PASSWORD
# ==============================
POST {{baseUrl}}/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "12345678"
}

###
# ==============================
# 👤 USUARIO ACTUAL
# ==============================
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
