@baseUrl = http://localhost:3000/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMjhjNWE4Yy1mZWFhLTQ4NWUtYmMyYS05YzMwYjFkNjNiYmUiLCJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NzIxMzA3OTksImV4cCI6MTc3MjEzMTY5OX0.IvhXnAUDVPZWtBeSAv18RhNmu3_FYH0uNY1u_3sb0XE
@refreshToken = b9d51f87ad91a17055fd8990e943aa992bc93cb6e235a58422da61ca2908237aa462e9c60d5d81fd989359532f9b53fccfafd00b721e92c9f88e5ae9800bab79

###
# ==============================
# 📝 REGISTER
# ==============================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Administrador",
  "email": "admin@mail.com",
  "password": "123456",
  "role": "admin",
  "companyId": null
}

###
# ==============================
# 🔐 LOGIN
# ==============================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "12345678"
}

###
# ==============================
# 🔄 REFRESH TOKEN
# ==============================
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT (revoca 1 sesión)
# ==============================
POST {{baseUrl}}/auth/logout
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###
# ==============================
# 🚪 LOGOUT ALL DEVICES
# ==============================
POST {{baseUrl}}/auth/logout-all
Authorization: Bearer {{accessToken}}

###
# ==============================
# 🔑 CAMBIAR PASSWORD
# ==============================
POST {{baseUrl}}/auth/change-password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "12345678"
}

###
# ==============================
# 👤 USUARIO ACTUAL
# ==============================
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}
