CREATE TABLE tenant.treasury_obligation_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar(150) NOT NULL,
  party_id uuid NOT NULL,
  category varchar(30) NOT NULL,
  treatment varchar(30) NOT NULL DEFAULT 'DIRECT_EXPENSE',
  service_product_id uuid,
  expense_account_id uuid,
  frequency varchar(20) NOT NULL DEFAULT 'MONTHLY',
  interval_months integer NOT NULL DEFAULT 1,
  start_date date NOT NULL,
  end_date date,
  occurrences integer,
  due_day integer NOT NULL,
  estimated_amount numeric(15,2) NOT NULL,
  net_amount numeric(15,2),
  currency_code varchar(10) NOT NULL DEFAULT 'ARS',
  variable_amount boolean NOT NULL DEFAULT false,
  notification_days jsonb NOT NULL DEFAULT '[7]'::jsonb,
  description varchar(500),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp(6) NOT NULL DEFAULT now(),
  updated_at timestamp(6),
  deleted_at timestamp(3),
  created_by uuid,
  updated_by uuid,
  deleted_by uuid
);

CREATE TABLE tenant.treasury_obligations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id uuid REFERENCES tenant.treasury_obligation_templates(id) ON DELETE SET NULL,
  party_id uuid NOT NULL,
  category varchar(30) NOT NULL,
  treatment varchar(30) NOT NULL DEFAULT 'DIRECT_EXPENSE',
  service_product_id uuid,
  expense_account_id uuid,
  net_amount numeric(15,2),
  period_key varchar(20) NOT NULL,
  description varchar(250) NOT NULL,
  issue_date date,
  due_date date NOT NULL,
  second_due_date date,
  estimated_amount numeric(15,2) NOT NULL DEFAULT 0,
  amount numeric(15,2),
  second_due_amount numeric(15,2),
  currency_code varchar(10) NOT NULL DEFAULT 'ARS',
  exchange_rate numeric(18,6),
  reference varchar(100),
  document_id uuid,
  payment_id uuid,
  status varchar(30) NOT NULL DEFAULT 'PLANNED',
  notification_days jsonb NOT NULL DEFAULT '[7]'::jsonb,
  notes varchar(500),
  confirmed_at timestamp(3),
  paid_at timestamp(3),
  created_at timestamp(6) NOT NULL DEFAULT now(),
  updated_at timestamp(6),
  deleted_at timestamp(3),
  created_by uuid,
  updated_by uuid,
  deleted_by uuid,
  CONSTRAINT treasury_obligations_template_period_key UNIQUE (template_id, period_key)
);

CREATE INDEX treasury_obligation_templates_party_active_idx ON tenant.treasury_obligation_templates(party_id, active);
CREATE INDEX treasury_obligations_party_status_due_idx ON tenant.treasury_obligations(party_id, status, due_date);
CREATE INDEX treasury_obligations_document_idx ON tenant.treasury_obligations(document_id);
CREATE INDEX treasury_obligations_payment_idx ON tenant.treasury_obligations(payment_id);
